### ISSUE TITLE
DIfference against http://swagger.io/

### ISSUE THREAD

**Issue by senzacionale** [lovedotnet/Love.Net.Help#16]
Hi, we are using http://swagger.io/ for our api documentation. Why you suggest to use your project. Is is easy to use, more powerful?

Thank you for response!

**Comment by senzacionale** [comment]
And why is in nuget "The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore."

That means out of support?

**Comment by xyting** [comment]
Dear @senzacionale Swagger is a very good and successful software. In some casts, however, have some limitation

- For English isn't their mother language developers, read XML comments by default is better.
- Swagger Enum use fields name by default(now can be configured to use underlying value).
- The API uses came-cast by default. (Love.Net.Help with the same with API).

Above are the major diff, and English isn't my mother language.

**Comment by senzacionale** [comment]
Thank you for fast response.

Why is in nuget "The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore." That means out of support?

Can I change a design of your "Love.Net.Help.UI"? To be more like in Swagger.UI?

**Comment by xyting** [comment]
@senzacionale [Love.Net.Help](http://www.nuget.org/packages/Love.Net.Help/1.0.1) list owners

- rigofunc (me)
- lotosbin@gmail.com
- love.net (the Team)

This nuget package used by my team and my friend team, so it's not deprecated and will be live for a long time.

And we will support all what we can.

Hope this help.

**Comment by xyting** [comment]
@senzacionale Happy your change, to whatever U like.

**Comment by xyting** [comment]
@senzacionale If you change the design of `Love.Net.Help.UI` to be more like in Swagger.UI, please give this repo a PR.
